version: '2.4'

services:  
    stats: &stats
      hostname: stats
      extends: 
        file: docker-compose-common-components.yml
        service: python
      command: stats_loop
      networks:
        - server1
        - common
      depends_on: 
        - postgres
        - redis