version: '2.4'

services:  
    auto_settings:
        hostname: auto_settings
        build: .
        extends:
          file: docker-compose-common-components.yml
          service: python
        command: auto_settings
    stats: &stats
      hostname: stats
      extends: 
        file: docker-compose-common-components.yml
        service: python
      command: stats_loop
      depends_on: 
        - postgres
        - redis