version: '2.4'

services:
  broadcast:
    build: .
    environment:
      LOGGING_LEVEL: 'DEBUG'
  logs_event_loop:
    build: .
    environment:
      LOGGING_LEVEL: 'DEBUG'
  stats:
    build: .
    environment:
      LOGGING_LEVEL: 'DEBUG'
  backend:
    environment:
      DJANGO_DEBUG: 'yes'
      LOGGING_LEVEL: 'DEBUG'
    build: .
  frontend:
    build:
      context: ./rcongui