version: '2.4'

services:
  broadcast:
    build: .
  logs_event_loop:
    build: .
  stats:
    build: .
  backend:
    build: .
    environment: 
      DJANGO_DEBUG: "true"
  frontend:
    build:
      context: ./rcongui
  redis:
    ports: 
      - 6379:6379
  postgres:
    ports:
      - 5432:5432
    