version: '2.4'

services:
  stats:
    hostname: stats
    extends:
      file: docker-compose-common-components.yml
      service: python
    command: bash -c "python -m rcon.cli init_db && python -m rcon.stats_loop"
  broadcast:
    hostname: broadcast
    extends: 
      file: docker-compose-common-components.yml
      service: python
    command: bash -c "python -m rcon.cli init_db && python -m rcon.broadcast"
  logs_event_loop:
    hostname: logs_event_loop
    extends: 
      file: docker-compose-common-components.yml
      service: python
    command: bash -c "python -m rcon.cli init_db && python -m rcon.cli log_loop"
  backend:
    hostname: api
    image: maresh/hll_rcon:latest
    extends: 
      file: docker-compose-common-components.yml
      service: python 
  frontend:    
    image: maresh/hll_rcon_frontend:latest
    ports:
      - ${RCONWEB_PORT}:80
    restart: always
    volumes: 
      - ./static:/static/
    environment: 
      RCONWEB_PASSWORD: ${RCONWEB_PASSWORD}
      RCONWEB_USERNAME: ${RCONWEB_USERNAME}
  redis:
    image: redislabs/redistimeseries
    restart: always
    volumes:
      - ./redis_data:/data
  postgres:
    image: postgres:12
    restart: always
    environment:
      # If a password is not defined this container will fail to create
      POSTGRES_PASSWORD: ${HLL_DB_PASSWORD}
      POSTGRES_USER: rcon
      POSTGRES_DB: rcon
      PGDATA: /data
    volumes:
      - ./db_data:/data

