version: '2.4'

services:
  supervisor:
    build: .
    environment:
      LOGGING_LEVEL: 'DEBUG'
  backend_1:
    environment:
      LOGGING_LEVEL: 'DEBUG'
    build: .
  frontend:
    build:
      context: ./rcongui
  redis:
    ports: 
      - 127.0.0.1:${HLL_REDIS_HOST_PORT:-6379}:6379
  postgres:
    ports:
      - ${HLL_DB_HOST_PORT:-5432}:5432