version: '2.4'

services:
  broadcast:
    image: maresh/hll_rcon_arm
  logs_event_loop:
    image: maresh/hll_rcon_arm
  backend_1:
    image: maresh/hll_rcon_arm
  frontend:
    image: maresh/hll_rcon_frontend_arm
  redis:
    image: arm32v7/redis:5
  postgres:
    image: arm32v7/postgres:12