version: '3.1'

services:
  broadcast:
    build: 
      context: .
      dockerfile: Dockerfile-arm32
    environment:
      HLL_HOST: ${HLL_HOST}
      HLL_PORT: ${HLL_PORT}
      HLL_PASSWORD: ${HLL_PASSWORD}
      BROADCAST_PATH: /conf/
      REDIS_URL: redis://redis:6379/0
      DB_URL: 'postgres://rcon:${HLL_DB_PASSWORD}@postgres:5432'
    restart: always
    links:
      - "redis:redis"
      - "postgres:postgres"
    volumes:
      - .:/conf
    command: bash -c "python -m rcon.cli init_db && python -m rcon.broadcast"
  logs_event_loop:
    build: 
      context: .
      dockerfile: Dockerfile-arm32
    command: bash -c "python -m rcon.cli init_db && python -m rcon.cli log_loop"
    restart: always
    environment:
      HLL_HOST: ${HLL_HOST}
      HLL_PORT: ${HLL_PORT}
      HLL_PASSWORD: ${HLL_PASSWORD}
      DB_URL: 'postgres://rcon:${HLL_DB_PASSWORD}@postgres:5432'
      REDIS_URL: redis://redis:6379/0
      LOGGING_LEVEL: INFO
      LOGGING_PATH: /logs/logs_event_loop.log
    volumes:
      - .:/logs
    links:
      - "redis:redis"
      - "postgres:postgres"
  backend:
    build: 
      context: .
      dockerfile: Dockerfile-arm32
    environment:
      HLL_HOST: ${HLL_HOST}
      HLL_PORT: ${HLL_PORT}
      HLL_PASSWORD: ${HLL_PASSWORD}
      LOGGING_PATH: /logs/backend.log
      LOGGING_LEVEL: INFO
      DJANGO_LOGGING_PATH: /logs/django.log
      REDIS_URL: redis://redis:6379/0
      DB_URL: 'postgres://rcon:${HLL_DB_PASSWORD}@postgres:5432'
    restart: always
    volumes:
      - .:/logs
    links:
      - "redis:redis"
      - "postgres:postgres"
  frontend:
    build:
      context: ./rcongui
      dockerfile: ./rcongui/Dockerfile-arm32
    ports:
      - ${RCONWEB_PORT}:80
    links:
      - "backend:backend"
    restart: always
    volumes:
      - ./pw:/pw
  redis:
    image: arm32v7/redis:5
    ports: # Exposing ports is only useful for local development
      - 127.0.0.1:${HLL_REDIS_HOST_PORT:-6379}:6379
    restart: always
  postgres:
    image: arm32v7/postgres:12
    restart: always
    environment:
      # If a password is not defined this container will fail to create
      POSTGRES_PASSWORD: ${HLL_DB_PASSWORD}
      POSTGRES_USER: rcon
      POSTGRES_DB: rcon
      PGDATA: /data
    volumes:
      - ./db_data:/data
    ports:
      - 127.0.0.1:${HLL_DB_HOST_PORT:-5432}:5432