version: '2.4'

services:
  broadcast: &broadcast
    hostname: broadcast
    extends: 
      file: docker-compose-common-components.yml
      service: python
    command: broadcast_loop
    depends_on: 
      - postgres
      - redis
  #stats: &stats
  # hostname: stats
  #  extends: 
  #    file: docker-compose-common-components.yml
  #    service: python
  #  command: stats_loop
  #  depends_on: 
  #    - postgres
  #    - redis
  logs_event_loop: &logs_event_loop
    hostname: logs_event_loop
    extends: 
      file: docker-compose-common-components.yml
      service: python
    command: log_loop
    depends_on: 
      - postgres
      - redis
  backend: &backend
    hostname: api
    extends: 
      file: docker-compose-common-components.yml
      service: python 
    command: web
    depends_on: 
        - postgres
        - redis
  frontend: &frontend    
    image: maresh/hll_rcon_frontend:latest
    ports:
      - ${RCONWEB_PORT}:80
    restart: always
    environment: 
      HLL_HOST: ${HLL_HOST}
      RCONWEB_PASSWORD: ${RCONWEB_PASSWORD}
      RCONWEB_USERNAME: ${RCONWEB_USERNAME}
    depends_on: 
        - backend
  redis:
    image: redislabs/redistimeseries:1.2.6
    ports: # Exposing ports is only useful for local development
      - 127.0.0.1:${HLL_REDIS_HOST_PORT:-6379}:6379
    restart: always
    volumes:
      - ./redis_data:/data
  postgres:
    image: postgres:12
    restart: always
    environment:
      # If a password is not defined this container will fail to create
      POSTGRES_PASSWORD: ${HLL_DB_PASSWORD}
      POSTGRES_USER: rcon
      POSTGRES_DB: rcon
      PGDATA: /data
    volumes:
      - ./db_data:/data
    ports:
      - 127.0.0.1:${HLL_DB_HOST_PORT:-5432}:5432


  ############ SERVER 2  #############
  broadcast_2:
    <<: *broadcast
    hostname: broadcast_2
    environment: &env2
      HLL_HOST: ${HLL_HOST_2}
      HLL_PORT: ${HLL_PORT_2}
      HLL_PASSWORD: ${HLL_PASSWORD_2}
      LOGGING_LEVEL: 'INFO'
      LOGGING_PATH: /logs/
      REDIS_URL: redis://redis:6379/1
      DB_URL: 'postgres://rcon:${HLL_DB_PASSWORD}@postgres:5432'
      DISCORD_WEBHOOK_AUDIT_LOG: ${DISCORD_WEBHOOK_AUDIT_LOG_2}
      RCONWEB_PASSWORD: ${RCONWEB_PASSWORD_2}
      RCONWEB_USERNAME: ${RCONWEB_USERNAME_2}
    restart: on-failure
  #stats_2: 
  #  <<: *stats
  #  hostname: stats_2
  #  environment: 
  #    <<: *env2
  #  restart: on-failure
  logs_event_loop_2: 
    <<: *logs_event_loop
    hostname: logs_event_loop_2
    environment: 
      <<: *env2
    restart: on-failure
  backend_2: 
    <<: *backend
    hostname: api_2
    environment: 
      <<: *env2
    restart: on-failure
  frontend_2: 
    <<: *frontend    
    ports:
      - ${RCONWEB_PORT_2}:80
    environment: 
      <<: *env2
    restart: on-failure