version: '3.1'

services:
  broadcast:
    build: .
    environment:
      HLL_HOST: ${HLL_HOST}
      HLL_PORT: ${HLL_PORT}
      HLL_PASSWORD: ${HLL_PASSWORD}
      BROADCAST_PATH: /conf/
    restart: always
    volumes:
      - .:/conf
    command: python -m rcon.broadcast
  backend:
    build: .
    environment:
      HLL_HOST: ${HLL_HOST}
      HLL_PORT: ${HLL_PORT}
      HLL_PASSWORD: ${HLL_PASSWORD}
      LOGGING_PATH: /logs/backend.log
      DJANGO_LOGGING_PATH: /logs/django.log
      REDIS_URL: redis://redis:6379/0
    restart: always
    volumes:
      - .:/logs
    links:
      - "redis:redis"
  frontend:
    build:
      context: ./rcongui
      args:
        REACT_APP_BATTLEMETRICS_SERVERID: ${REACT_APP_BATTLEMETRICS_SERVERID}
    ports:
      - 8010:80
    links:
      - "backend:backend"
    restart: always
    volumes:
      - ./pw:/pw
  redis:
    image: redis:5
    ports: # Exposing ports is only useful for local development
      - 127.0.0.1:6379:6379
    restart: always