version: '2.4'

services:  
    auto_settings:
      hostname: auto_settings
      build: .
      extends:
        file: docker-compose-common-components.yml
        service: python
      command: auto_settings
      networks:
        - server1
        - common
    vote_map:
      hostname: vote_map
      image: rcon_test
      build: 
        dockerfile: Dockerfile-exp
        context: .
      extends:
        file: docker-compose-common-components.yml
        service: python
      command: python vote_nextmap.py
      restart: always
      networks:
        - server1
        - common
    stats: &stats
      hostname: stats
      extends: 
        file: docker-compose-common-components.yml
        service: python
      command: stats_loop
      networks:
        - server1
        - common
      depends_on: 
        - postgres
        - redis