version: '2.4'

services:  
    auto_settings:
        hostname: auto_settings
        build: .
        extends:
          file: docker-compose-common-components.yml
          service: python
        command: bash -c "python -m rcon.cli init_db && python -m rcon.auto_settings"