version: '2.4'

services:
  broadcast:
    build: .
  logs_event_loop:
    build: .
  backend:
    build: .
    environment: 
      DJANGO_DEBUG: "true"
  frontend:
    build:
      context: ./rcongui