version: '2.4'

services:
  broadcast:
    extends: 
      file: docker-compose-common-components.yml
      service: python
    command: bash -c "python -m rcon.cli init_db && python -m rcon.broadcast"
    links:
      - "redis:redis"
      - "postgres:postgres"
  stats:
    extends: 
      file: docker-compose-common-components.yml
      service: python
    command: bash -c "python -m rcon.cli init_db && python -m rcon.stats_loop"
    links:
      - "redis:redis"
      - "postgres:postgres"
  logs_event_loop:
    extends: 
      file: docker-compose-common-components.yml
      service: python
    command: bash -c "python -m rcon.cli init_db && python -m rcon.cli log_loop"
    links:
      - "redis:redis"
      - "postgres:postgres"
  backend:
    image: maresh/hll_rcon:latest
    extends: 
      file: docker-compose-common-components.yml
      service: python
    links:
      - "redis:redis"
      - "postgres:postgres"
    volumes:
      - .:/logs
  frontend:    
    image: maresh/hll_rcon_frontend:latest
    ports:
      - ${RCONWEB_PORT}:80
    links:
      - "backend:backend"
    restart: always
    environment: 
      RCONWEB_PASSWORD: ${RCONWEB_PASSWORD}
      RCONWEB_USERNAME: ${RCONWEB_USERNAME}
  redis:
    image: redislabs/redistimeseries
    ports: # Exposing ports is only useful for local development
      - 127.0.0.1:${HLL_REDIS_HOST_PORT:-6379}:6379
    restart: always
    volumes:
      - ./redis_data:/data
  postgres:
    image: postgres:12
    restart: always
    environment:
      # If a password is not defined this container will fail to create
      POSTGRES_PASSWORD: ${HLL_DB_PASSWORD}
      POSTGRES_USER: rcon
      POSTGRES_DB: rcon
      PGDATA: /data
    volumes:
      - ./db_data:/data
    ports:
      - 127.0.0.1:${HLL_DB_HOST_PORT:-5432}:5432